language: cpp
compiler: 
    - gcc
notifications:
    email: false
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'versioninfo(); Pkg.init();'
    - julia -e 'Pkg.add("Datetime"); Pkg.clone("https://github.com/milktrader/Jig.jl.git"); Pkg.clone("https://github.com/JuliaQuant/MarketData.jl.git")'
    - mkdir -p ~/.julia/Series
    - cp -R ./* ~/.julia/Series/
    - julia ./test/all.jl
